on: push
name: 🚀 Deploy - Main
jobs:
  web-deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    name: 🎉 Deploy to https://zahro.partnerku.online/
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code 
        uses: actions/checkout@v2

      - name: 🚫 Remove Meta Files & Folders
        run: |
          rm -rf .github
          rm login.zip "login copy.zip" 

      - name: 💯 Configuration for Production
        run: |
          sed -i 's/$hostname='localhost'/$hostname='${{ secrets.db_host }}'/g' koneksi.php
          sed -i 's/$username='root'/$username='${{ secrets.db_user }}'/g' koneksi.php
          sed -i 's/$password=''/$password='${{ secrets.db_password }}'/g' koneksi.php
          sed -i 's/$database='pw'/$database='${{ secrets.db_name }}'/g' koneksi.php

      - name: 💾 Sync files to Server 📡
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.partnerku.online
          username: ${{ secrets.ftp_email }}
          password: ${{ secrets.ftp_password }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
